:sparkles: bot structure created
mukta-strot/MarathiNotMaharashtrianBot pull request #2
Opened 2021-12-03 16:32 UTC by vinodnimbalkar

# Description

Need to add bot functionality and code structure

Fixes # (issue)
No issue found, its new feature

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?
Sorry, not tested, testing should be done on the local system before deployment to production.

**Test Configuration**:
* Browser: 
* Browser version: 
* OS: Ubuntu 20.04 LTS
* Python version: 3.8.10

2021-12-03 23:48 UTC, sanketgarade commented
Hi Vinod 👋 

Thank for sending the PR. 

Before I merge this, I had some basic questions. 

I created a post under discussions here #3. Can we discuss there?

2021-12-04 13:05 UTC, sanketgarade requested changes

2021-12-04 13:05 UTC, sanketgarade commented on README.md
>  - [Reddit link](https://reddit.com/user/SomaliNotSomalianbot/)
ही ओळ चुकून उडवली गेली आहे वाटतं. ती ठीक करून देऊ शकता का? मग PR merge करतो.

2021-12-04 14:16 UTC, vinodnimbalkar commented on README.md
>  - [Reddit link](https://reddit.com/user/SomaliNotSomalianbot/)
![image](https://user-images.githubusercontent.com/16244310/144712038-25060962-5d67-43cf-8588-4d97f177b3e5.png)

कोणतीही ओळ उडवली गेली नाहीये, ओळ क्रमांक ३ मध्ये **सुचवेल.** या शब्दानंतर एक रिकामी जागा (स्पेस) होती म्हणून माझा कोड एडिटर ने तो स्पेस आपोआप उडवला असेल.
ओळ क्रमांक ११ डावीकडे उडली गेली असे वाटत आहे कारण **SomaliNotSomalianBot.** नंतर एक रिकामी जागा (स्पेस) होती, पण त्याचवेळी उजवीकडे पाहिलं तर समजेल कि ती ओळ पुन्हा रिकामी जागा काडून लगेच जोडली गेली आहे. 
ओळ क्रमांक १३ मध्ये दोन रिकाम्या जागा आहेत, त्यामुळे ती ओळ उडाली गेली आहे पण त्या ओळीची जागा क्रमांक २० ने घेतली आहे.
आधीच्या रिकामा जागा पाहायच्या असल्यास [येथे](https://github.com/mukta-strot/MarathiNotMaharashtrianBot/edit/main/README.md) भेट देऊ शकता.

2021-12-04 14:26 UTC, sanketgarade commented on README.md
>  - [Reddit link](https://reddit.com/user/SomaliNotSomalianbot/)
आलं लक्षात. माझी मोबाईल वर बघताना चूक झाली. 😬🙏🏽

2021-12-04 14:26 UTC, merged